version: '3'
services:
    card_db:
        image: "mariadb:latest"
        command: --max-connections 1000 --innodb-lock-wait-timeout 300 --max-prepared-stmt-count 50000
        volumes:
            - ../../container-volumes/mariadb:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "db_password"
            MYSQL_DATABASE: "mtg_cards"
            MYSQL_USER: "app_user"
            MYSQL_PASSWORD: "app_db_password"
    phpmyadmin:
        image: "phpmyadmin/phpmyadmin:latest"
        environment:
            PMA_HOST: "card_db"
            PMA_USER: "root"
            PMA_PASSWORD: "db_password"
            PMA_ABSOLUTE_URI: "http://phpmyadmin/phpmyadmin/"
    card_prices_db:
        image: "influxdb:latest"
        volumes:
            - ../../container-volumes/influxdb:/var/lib/influxdb
        environment:
            INFLUXDB_DB: "mtg_cards"
            INFLUXDB_ADMIN_USER: "admin_user"
            INFLUXDB_ADMIN_PASSWORD: "admin_password"
            INFLUXDB_USER: "app_user"
            INFLUXDB_USER_PASSWORD: "app_db_password"
    grafana:
        image: "grafana/grafana:latest"
        volumes:
            - ../../container-volumes/grafana:/var/lib/grafana
        environment:
            #GF_DATABASE_TYPE: mysql
            #GF_DATABASE_HOST: card_db
            #GF_DATABASE_NAME: grafana
            #GF_DATABASE_USER: app_user
            #GF_DATABASE_PASSWORD: add_db_password
            GF_SERVER_ROOT_URL: "http://grafana:3000/grafana/"
            GF_SERVER_SERVE_FROM_SUB_PATH: "true"
            GF_SECURITY_ADMIN_USER: "grafana_admin"
            GF_SECURITY_ADMIN_PASSWORD: "grafana_admin_password"
    card_importer:
        build:
            context: ../../go/
            dockerfile: ../docker/card-importer/Dockerfile
        volumes:
            - ../../container-volumes/card-importer:/var/card-importer/card-data
            - ../../web_content/static_content/card_face_images:/var/card-importer/card-images
    nginx:
        image: "nginx:latest"
        volumes:
            - ../../web_content:/usr/share/nginx/html
            - ../../nginx/conf:/etc/nginx
            - ../../nginx/conf.d:/etc/nginx/conf.d
            - ../../container-volumes/nginx/var-log:/var/log
            - ../../container-volumes/nginx/var-run:/var/run
        ports:
            - "80:80"
    hydra:
        image: "oryd/hydra:latest"
        command: serve all --dangerous-force-http
        environment:
            SECRETS_SYSTEM: "this_is_a_temporary_development_system_secret"
            DSN: "mysql://hydra_user:hydra_password@tcp(card_db)/hydra"
            URLS_SELF_ISSUER: "http://192.168.50.185/"
            URLS_CONSENT: "http://192.168.50.185:3000/auth/consent"
            URLS_LOGIN: "http://192.168.50.185:3000/auth/login"
            SERVE_PUBLIC_CORS_ENABLED: "true"
            SERVE_PUBLIC_CORS_ALLOWED_ORIGINS: "[http://192.168.50.185:3000]"
            SERVE_PUBLIC_CORS_ALLOWED_METHODS: "[POST,GET,PUT,PATCH,DELETE]"
            SERVE_PUBLIC_CORS_ALLOWED_HEADERS: "[Authorization]"
            SERVE_PUBLIC_CORS_EXPOSED_HEADERS: "[Content-Type]"

