// Code generated by "stringer -type=RequestType"; DO NOT EDIT.

package backend

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ApiTypesRequest-0]
	_ = x[LoginChallengeCheck-1]
	_ = x[LoginRequest-2]
	_ = x[CardSearchRequest-3]
	_ = x[CardDetailRequest-4]
}

const _RequestType_name = "ApiTypesRequestLoginChallengeCheckLoginRequestCardSearchRequestCardDetailRequest"

var _RequestType_index = [...]uint8{0, 15, 34, 46, 63, 80}

func (i RequestType) String() string {
	if i < 0 || i >= RequestType(len(_RequestType_index)-1) {
		return "RequestType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RequestType_name[_RequestType_index[i]:_RequestType_index[i+1]]
}
